import type { BaseConfig } from "./types";

export const defaults: BaseConfig = {
  outdir: "dist",
  ext: ".js",
  polyfills: [],
  inject: [],
  loader: {},
  clean: true,
  format: "cjs",
  ignoreTypes: false,
  import: [],
  minify: false,
  nodeOptions: [],
  reset: false,
  killSignal: "SIGTERM",
  run: false,
  tsconfig: "tsconfig.json",
  sourcemap: false,
  watch: false,
  logLevel: "info",
  repl: false,
  test: false,
  testPattern: "**/*.test.{ts,js}",
  inspect: false,
  inspectBrk: false,
  parallel: false,
};
